<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Compétences | PORTFOLIO</title>
      <!-- CSS BUNDLE MIN -->
      <link rel="stylesheet" href="../../public/css/swiper-bundle.min.css">

      <!-- CSS -->
      <link rel="stylesheet" href="../../public/css/master.css">
      <link rel="stylesheet" href="../../public/css/slider.css">
  </head>

  <body>
    <form action="/languages" method="POST">
      <header class="container-header">
          <div>
            <p>
            <h1 class="txt-al-center">PERRICHET KILLIAN</h1>
            </p>
            <p>
            <h1 class="txt-al-center">DEVELOPPEUR WEB</h1>
            </p>
          </div>
      </header>
      <nav class="container-nav">
          <a href="/" class="m-16">Accueil</a>
          <a href="/etude" class="m-16">Étude</a>
          <a href="/projet" class="m-16">Projet</a>
          <a href="#" class="m-16">Hobbies</a>
      </nav>
      <main>
          <h2 style="color: white; text-align: center;">Languages maitrisés</h2>
          <div class="slider">
            <div class="slide-container swiper">
              <div class="slide-content">
                <div class="card-wrapper swiper-wrapper">
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image">
                        <img src="../../public/images/HTML-logo.webp" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">HTML 5</h2>
                      <p class="description">he lorem text the section that contains header with having open
                        functionality. Lorem dolor sit amet consectetur adipisicing elit.</p>
          
                      
                    </div>
                  </div>
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image">
                        <img src="../../public/images/Css-logo.png" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">CSS 3</h2>
                      <p class="description">The lorem text the section that contains header with having open
                        functionality. Lorem dolor sit amet consectetur adipisicing elit.</p>
          
                      
                    </div>
                  </div>
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image">
                        <img src="../../public/images/js-logo.webp" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">Javascript</h2>
                      <p class="description">The lorem text the section that contains header with having open
                        functionality. Lorem dolor sit amet consectetur adipisicing elit.</p>
          
                      
                    </div>
                  </div>
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image">
                        <img src="../../public/images/Php-logo.png" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">PHP</h2>
                      <p class="description">The lorem text the section that contains header with having open
                        functionality. Lorem dolor sit amet consectetur adipisicing elit.</p>
                    </div>
                  </div>
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image">
                        <img src="../../public/images/SQL-logo.jpg" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">SQL</h2>
                      <p class="description">The lorem text the section that contains header with having open
                        functionality. Lorem dolor sit amet consectetur adipisicing elit.</p>
          
                      
                    </div>
                  </div>
                  <div class="card swiper-slide">
                    <div class="image-content">
                      <span class="overlay"></span>
          
                      <div class="card-image">
                        <img src="../../public/images/Angular-logo.png" alt="" class="card-img">
                      </div>
                    </div>
          
                    <div class="card-content">
                      <h2 class="name">Angular</h2>
                      <p class="description">The lorem text the section that contains header with having open
                        functionality. Lorem dolor sit amet consectetur adipisicing elit.</p>
          
                      
                    </div>
                  </div>
                </div>
              </div>
          
              <div class="swiper-button-next swiper-navBtn"></div>
              <div class="swiper-button-prev swiper-navBtn"></div>
              <div class="swiper-pagination"></div>
            </div>
          </div>
      </main>
      <footer class="footer p-32">
          <div class="footer footdiv">
            <h5>Mes réseaux</h5>
            <a class="" href="#">
              <img src="../../public/images/github(1).svg" alt="Logo_Github" width="30px">
            </a>
            <a class="" href="#">
              <img src="../../public/images/linkedin(1).svg" alt="Logo_Linkedin" width="30px">
            </a>
          </div>
          <div class="">
            <h5>copyright &#169; 2023 PERRICHET Killian</h5>
          </div>
      </footer>
    </form>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
  <script src="../../public/js/script.js"></script>
</html>